# Generated by Django 4.0.10 on 2024-01-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_vendor'),
        ('orders', '0002_remove_order_products_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='products.product'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
