# Generated by Django 4.0.10 on 2024-01-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_items_order_products_alter_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
