# Generated by Django 4.0.10 on 2024-01-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='display_name',
            field=models.CharField(default='Vendor', max_length=255),
            preserve_default=False,
        ),
    ]
