# Generated by Django 4.0.10 on 2024-01-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_vendor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Supermarket', 'Supermarket'), ('Grocery', 'Grocery'), ('Bakery', 'Bakery')], max_length=255),
        ),
    ]
