# Generated by Django 4.0.10 on 2024-01-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='type',
            field=models.CharField(choices=[('Round-up', 'Round-up'), ('Points', 'Points')], default='Points', max_length=10),
        ),
    ]
