# Generated by Django 4.0.10 on 2024-01-18 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_round_up'),
        ('donations', '0002_donation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
